// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/chart/config.proto

package io.winhong.pass.hapi.chart;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.chart.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string raw = 1;</code>
     */
    java.lang.String getRaw();
    /**
     * <code>optional string raw = 1;</code>
     */
    com.google.protobuf.ByteString
        getRawBytes();

    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
    getValues();
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */
    java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
    getValuesMap();
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrDefault(
        java.lang.String key,
        io.winhong.pass.hapi.chart.ConfigOuterClass.Value defaultValue);
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Config supplies values to the parametrizable templates of a chart.
   * </pre>
   *
   * Protobuf type {@code hapi.chart.Config}
   */
  public  static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.chart.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      raw_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              raw_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
              values = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(values.getKey(), values.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.winhong.pass.hapi.chart.ConfigOuterClass.Config.class, io.winhong.pass.hapi.chart.ConfigOuterClass.Config.Builder.class);
    }

    private int bitField0_;
    public static final int RAW_FIELD_NUMBER = 1;
    private volatile java.lang.Object raw_;
    /**
     * <code>optional string raw = 1;</code>
     */
    public java.lang.String getRaw() {
      java.lang.Object ref = raw_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        raw_ = s;
        return s;
      }
    }
    /**
     * <code>optional string raw = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRawBytes() {
      java.lang.Object ref = raw_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        raw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 2;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>newDefaultInstance(
                  io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_ValuesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  io.winhong.pass.hapi.chart.ConfigOuterClass.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> values_;
    private com.google.protobuf.MapField<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    public java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrDefault(
        java.lang.String key,
        io.winhong.pass.hapi.chart.ConfigOuterClass.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
     */

    public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRawBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, raw_);
      }
      for (java.util.Map.Entry<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
        values = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, values);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRawBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, raw_);
      }
      for (java.util.Map.Entry<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
        values = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, values);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.winhong.pass.hapi.chart.ConfigOuterClass.Config)) {
        return super.equals(obj);
      }
      io.winhong.pass.hapi.chart.ConfigOuterClass.Config other = (io.winhong.pass.hapi.chart.ConfigOuterClass.Config) obj;

      boolean result = true;
      result = result && getRaw()
          .equals(other.getRaw());
      result = result && internalGetValues().equals(
          other.internalGetValues());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RAW_FIELD_NUMBER;
      hash = (53 * hash) + getRaw().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.winhong.pass.hapi.chart.ConfigOuterClass.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Config supplies values to the parametrizable templates of a chart.
     * </pre>
     *
     * Protobuf type {@code hapi.chart.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.chart.Config)
        io.winhong.pass.hapi.chart.ConfigOuterClass.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.winhong.pass.hapi.chart.ConfigOuterClass.Config.class, io.winhong.pass.hapi.chart.ConfigOuterClass.Config.Builder.class);
      }

      // Construct using io.winhong.pass.hapi.chart.ConfigOuterClass.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        raw_ = "";

        internalGetMutableValues().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Config_descriptor;
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Config getDefaultInstanceForType() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.Config.getDefaultInstance();
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Config build() {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Config buildPartial() {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Config result = new io.winhong.pass.hapi.chart.ConfigOuterClass.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.raw_ = raw_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.winhong.pass.hapi.chart.ConfigOuterClass.Config) {
          return mergeFrom((io.winhong.pass.hapi.chart.ConfigOuterClass.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.winhong.pass.hapi.chart.ConfigOuterClass.Config other) {
        if (other == io.winhong.pass.hapi.chart.ConfigOuterClass.Config.getDefaultInstance()) return this;
        if (!other.getRaw().isEmpty()) {
          raw_ = other.raw_;
          onChanged();
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.winhong.pass.hapi.chart.ConfigOuterClass.Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object raw_ = "";
      /**
       * <code>optional string raw = 1;</code>
       */
      public java.lang.String getRaw() {
        java.lang.Object ref = raw_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          raw_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string raw = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRawBytes() {
        java.lang.Object ref = raw_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          raw_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string raw = 1;</code>
       */
      public Builder setRaw(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        raw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string raw = 1;</code>
       */
      public Builder clearRaw() {
        
        raw_ = getDefaultInstance().getRaw();
        onChanged();
        return this;
      }
      /**
       * <code>optional string raw = 1;</code>
       */
      public Builder setRawBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        raw_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> values_;
      private com.google.protobuf.MapField<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrDefault(
          java.lang.String key,
          io.winhong.pass.hapi.chart.ConfigOuterClass.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        getMutableValues().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableValues().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */
      public Builder putValues(
          java.lang.String key,
          io.winhong.pass.hapi.chart.ConfigOuterClass.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableValues().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .hapi.chart.Value&gt; values = 2;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, io.winhong.pass.hapi.chart.ConfigOuterClass.Value> values) {
        getMutableValues().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.chart.Config)
    }

    // @@protoc_insertion_point(class_scope:hapi.chart.Config)
    private static final io.winhong.pass.hapi.chart.ConfigOuterClass.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.winhong.pass.hapi.chart.ConfigOuterClass.Config();
    }

    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public io.winhong.pass.hapi.chart.ConfigOuterClass.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.chart.Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * Value describes a configuration value as a string.
   * </pre>
   *
   * Protobuf type {@code hapi.chart.Value}
   */
  public  static final class Value extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.chart.Value)
      ValueOrBuilder {
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Value() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Value_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.winhong.pass.hapi.chart.ConfigOuterClass.Value.class, io.winhong.pass.hapi.chart.ConfigOuterClass.Value.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.winhong.pass.hapi.chart.ConfigOuterClass.Value)) {
        return super.equals(obj);
      }
      io.winhong.pass.hapi.chart.ConfigOuterClass.Value other = (io.winhong.pass.hapi.chart.ConfigOuterClass.Value) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.winhong.pass.hapi.chart.ConfigOuterClass.Value prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Value describes a configuration value as a string.
     * </pre>
     *
     * Protobuf type {@code hapi.chart.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.chart.Value)
        io.winhong.pass.hapi.chart.ConfigOuterClass.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.winhong.pass.hapi.chart.ConfigOuterClass.Value.class, io.winhong.pass.hapi.chart.ConfigOuterClass.Value.Builder.class);
      }

      // Construct using io.winhong.pass.hapi.chart.ConfigOuterClass.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.internal_static_hapi_chart_Value_descriptor;
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getDefaultInstanceForType() {
        return io.winhong.pass.hapi.chart.ConfigOuterClass.Value.getDefaultInstance();
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Value build() {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.winhong.pass.hapi.chart.ConfigOuterClass.Value buildPartial() {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Value result = new io.winhong.pass.hapi.chart.ConfigOuterClass.Value(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.winhong.pass.hapi.chart.ConfigOuterClass.Value) {
          return mergeFrom((io.winhong.pass.hapi.chart.ConfigOuterClass.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.winhong.pass.hapi.chart.ConfigOuterClass.Value other) {
        if (other == io.winhong.pass.hapi.chart.ConfigOuterClass.Value.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.winhong.pass.hapi.chart.ConfigOuterClass.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.winhong.pass.hapi.chart.ConfigOuterClass.Value) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.chart.Value)
    }

    // @@protoc_insertion_point(class_scope:hapi.chart.Value)
    private static final io.winhong.pass.hapi.chart.ConfigOuterClass.Value DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.winhong.pass.hapi.chart.ConfigOuterClass.Value();
    }

    public static io.winhong.pass.hapi.chart.ConfigOuterClass.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Value>
        PARSER = new com.google.protobuf.AbstractParser<Value>() {
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Value(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Value> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    public io.winhong.pass.hapi.chart.ConfigOuterClass.Value getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_chart_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_chart_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_chart_Config_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_chart_Config_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_chart_Value_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_chart_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027hapi/chart/config.proto\022\nhapi.chart\"\207\001" +
      "\n\006Config\022\013\n\003raw\030\001 \001(\t\022.\n\006values\030\002 \003(\0132\036." +
      "hapi.chart.Config.ValuesEntry\032@\n\013ValuesE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022 \n\005value\030\002 \001(\0132\021.hapi." +
      "chart.Value:\0028\001\"\026\n\005Value\022\r\n\005value\030\001 \001(\tB" +
      "#\n!io.winhong.pass.hapi.chartb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hapi_chart_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hapi_chart_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_chart_Config_descriptor,
        new java.lang.String[] { "Raw", "Values", });
    internal_static_hapi_chart_Config_ValuesEntry_descriptor =
      internal_static_hapi_chart_Config_descriptor.getNestedTypes().get(0);
    internal_static_hapi_chart_Config_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_chart_Config_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_hapi_chart_Value_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hapi_chart_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_chart_Value_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
