// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/release/info.proto

package io.winhong.pass.hapi.release;

public final class InfoOuterClass {
  private InfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.release.Info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    io.winhong.pass.hapi.release.StatusOuterClass.Status getStatus();
    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    boolean hasFirstDeployed();
    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    com.google.protobuf.Timestamp getFirstDeployed();
    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getFirstDeployedOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    boolean hasLastDeployed();
    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    com.google.protobuf.Timestamp getLastDeployed();
    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastDeployedOrBuilder();

    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    boolean hasDeleted();
    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    com.google.protobuf.Timestamp getDeleted();
    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder();

    /**
     * <pre>
     * Description is human-friendly "log entry" about this release.
     * </pre>
     *
     * <code>optional string Description = 5;</code>
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * Description is human-friendly "log entry" about this release.
     * </pre>
     *
     * <code>optional string Description = 5;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * <pre>
   * Info describes release information.
   * </pre>
   *
   * Protobuf type {@code hapi.release.Info}
   */
  public  static final class Info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.release.Info)
      InfoOrBuilder {
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Info() {
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(io.winhong.pass.hapi.release.StatusOuterClass.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (firstDeployed_ != null) {
                subBuilder = firstDeployed_.toBuilder();
              }
              firstDeployed_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(firstDeployed_);
                firstDeployed_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastDeployed_ != null) {
                subBuilder = lastDeployed_.toBuilder();
              }
              lastDeployed_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastDeployed_);
                lastDeployed_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (deleted_ != null) {
                subBuilder = deleted_.toBuilder();
              }
              deleted_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deleted_);
                deleted_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.winhong.pass.hapi.release.InfoOuterClass.internal_static_hapi_release_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.winhong.pass.hapi.release.InfoOuterClass.internal_static_hapi_release_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.winhong.pass.hapi.release.InfoOuterClass.Info.class, io.winhong.pass.hapi.release.InfoOuterClass.Info.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private io.winhong.pass.hapi.release.StatusOuterClass.Status status_;
    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    public io.winhong.pass.hapi.release.StatusOuterClass.Status getStatus() {
      return status_ == null ? io.winhong.pass.hapi.release.StatusOuterClass.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>optional .hapi.release.Status status = 1;</code>
     */
    public io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    public static final int FIRST_DEPLOYED_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp firstDeployed_;
    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    public boolean hasFirstDeployed() {
      return firstDeployed_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    public com.google.protobuf.Timestamp getFirstDeployed() {
      return firstDeployed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstDeployed_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFirstDeployedOrBuilder() {
      return getFirstDeployed();
    }

    public static final int LAST_DEPLOYED_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp lastDeployed_;
    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    public boolean hasLastDeployed() {
      return lastDeployed_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    public com.google.protobuf.Timestamp getLastDeployed() {
      return lastDeployed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastDeployed_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastDeployedOrBuilder() {
      return getLastDeployed();
    }

    public static final int DELETED_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp deleted_;
    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    public boolean hasDeleted() {
      return deleted_ != null;
    }
    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    public com.google.protobuf.Timestamp getDeleted() {
      return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
    }
    /**
     * <pre>
     * Deleted tracks when this object was deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
      return getDeleted();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * Description is human-friendly "log entry" about this release.
     * </pre>
     *
     * <code>optional string Description = 5;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Description is human-friendly "log entry" about this release.
     * </pre>
     *
     * <code>optional string Description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != null) {
        output.writeMessage(1, getStatus());
      }
      if (firstDeployed_ != null) {
        output.writeMessage(2, getFirstDeployed());
      }
      if (lastDeployed_ != null) {
        output.writeMessage(3, getLastDeployed());
      }
      if (deleted_ != null) {
        output.writeMessage(4, getDeleted());
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStatus());
      }
      if (firstDeployed_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFirstDeployed());
      }
      if (lastDeployed_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLastDeployed());
      }
      if (deleted_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDeleted());
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.winhong.pass.hapi.release.InfoOuterClass.Info)) {
        return super.equals(obj);
      }
      io.winhong.pass.hapi.release.InfoOuterClass.Info other = (io.winhong.pass.hapi.release.InfoOuterClass.Info) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && (hasFirstDeployed() == other.hasFirstDeployed());
      if (hasFirstDeployed()) {
        result = result && getFirstDeployed()
            .equals(other.getFirstDeployed());
      }
      result = result && (hasLastDeployed() == other.hasLastDeployed());
      if (hasLastDeployed()) {
        result = result && getLastDeployed()
            .equals(other.getLastDeployed());
      }
      result = result && (hasDeleted() == other.hasDeleted());
      if (hasDeleted()) {
        result = result && getDeleted()
            .equals(other.getDeleted());
      }
      result = result && getDescription()
          .equals(other.getDescription());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      if (hasFirstDeployed()) {
        hash = (37 * hash) + FIRST_DEPLOYED_FIELD_NUMBER;
        hash = (53 * hash) + getFirstDeployed().hashCode();
      }
      if (hasLastDeployed()) {
        hash = (37 * hash) + LAST_DEPLOYED_FIELD_NUMBER;
        hash = (53 * hash) + getLastDeployed().hashCode();
      }
      if (hasDeleted()) {
        hash = (37 * hash) + DELETED_FIELD_NUMBER;
        hash = (53 * hash) + getDeleted().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.InfoOuterClass.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.winhong.pass.hapi.release.InfoOuterClass.Info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Info describes release information.
     * </pre>
     *
     * Protobuf type {@code hapi.release.Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.release.Info)
        io.winhong.pass.hapi.release.InfoOuterClass.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.winhong.pass.hapi.release.InfoOuterClass.internal_static_hapi_release_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.winhong.pass.hapi.release.InfoOuterClass.internal_static_hapi_release_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.winhong.pass.hapi.release.InfoOuterClass.Info.class, io.winhong.pass.hapi.release.InfoOuterClass.Info.Builder.class);
      }

      // Construct using io.winhong.pass.hapi.release.InfoOuterClass.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        if (firstDeployedBuilder_ == null) {
          firstDeployed_ = null;
        } else {
          firstDeployed_ = null;
          firstDeployedBuilder_ = null;
        }
        if (lastDeployedBuilder_ == null) {
          lastDeployed_ = null;
        } else {
          lastDeployed_ = null;
          lastDeployedBuilder_ = null;
        }
        if (deletedBuilder_ == null) {
          deleted_ = null;
        } else {
          deleted_ = null;
          deletedBuilder_ = null;
        }
        description_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.winhong.pass.hapi.release.InfoOuterClass.internal_static_hapi_release_Info_descriptor;
      }

      public io.winhong.pass.hapi.release.InfoOuterClass.Info getDefaultInstanceForType() {
        return io.winhong.pass.hapi.release.InfoOuterClass.Info.getDefaultInstance();
      }

      public io.winhong.pass.hapi.release.InfoOuterClass.Info build() {
        io.winhong.pass.hapi.release.InfoOuterClass.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.winhong.pass.hapi.release.InfoOuterClass.Info buildPartial() {
        io.winhong.pass.hapi.release.InfoOuterClass.Info result = new io.winhong.pass.hapi.release.InfoOuterClass.Info(this);
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (firstDeployedBuilder_ == null) {
          result.firstDeployed_ = firstDeployed_;
        } else {
          result.firstDeployed_ = firstDeployedBuilder_.build();
        }
        if (lastDeployedBuilder_ == null) {
          result.lastDeployed_ = lastDeployed_;
        } else {
          result.lastDeployed_ = lastDeployedBuilder_.build();
        }
        if (deletedBuilder_ == null) {
          result.deleted_ = deleted_;
        } else {
          result.deleted_ = deletedBuilder_.build();
        }
        result.description_ = description_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.winhong.pass.hapi.release.InfoOuterClass.Info) {
          return mergeFrom((io.winhong.pass.hapi.release.InfoOuterClass.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.winhong.pass.hapi.release.InfoOuterClass.Info other) {
        if (other == io.winhong.pass.hapi.release.InfoOuterClass.Info.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasFirstDeployed()) {
          mergeFirstDeployed(other.getFirstDeployed());
        }
        if (other.hasLastDeployed()) {
          mergeLastDeployed(other.getLastDeployed());
        }
        if (other.hasDeleted()) {
          mergeDeleted(other.getDeleted());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.winhong.pass.hapi.release.InfoOuterClass.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.winhong.pass.hapi.release.InfoOuterClass.Info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.winhong.pass.hapi.release.StatusOuterClass.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.winhong.pass.hapi.release.StatusOuterClass.Status, io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder, io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public io.winhong.pass.hapi.release.StatusOuterClass.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? io.winhong.pass.hapi.release.StatusOuterClass.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public Builder setStatus(io.winhong.pass.hapi.release.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public Builder setStatus(
          io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public Builder mergeStatus(io.winhong.pass.hapi.release.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              io.winhong.pass.hapi.release.StatusOuterClass.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder getStatusBuilder() {
        
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      public io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              io.winhong.pass.hapi.release.StatusOuterClass.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>optional .hapi.release.Status status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.winhong.pass.hapi.release.StatusOuterClass.Status, io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder, io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder>
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.winhong.pass.hapi.release.StatusOuterClass.Status, io.winhong.pass.hapi.release.StatusOuterClass.Status.Builder, io.winhong.pass.hapi.release.StatusOuterClass.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      private com.google.protobuf.Timestamp firstDeployed_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> firstDeployedBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public boolean hasFirstDeployed() {
        return firstDeployedBuilder_ != null || firstDeployed_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public com.google.protobuf.Timestamp getFirstDeployed() {
        if (firstDeployedBuilder_ == null) {
          return firstDeployed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstDeployed_;
        } else {
          return firstDeployedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public Builder setFirstDeployed(com.google.protobuf.Timestamp value) {
        if (firstDeployedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          firstDeployed_ = value;
          onChanged();
        } else {
          firstDeployedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public Builder setFirstDeployed(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (firstDeployedBuilder_ == null) {
          firstDeployed_ = builderForValue.build();
          onChanged();
        } else {
          firstDeployedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public Builder mergeFirstDeployed(com.google.protobuf.Timestamp value) {
        if (firstDeployedBuilder_ == null) {
          if (firstDeployed_ != null) {
            firstDeployed_ =
              com.google.protobuf.Timestamp.newBuilder(firstDeployed_).mergeFrom(value).buildPartial();
          } else {
            firstDeployed_ = value;
          }
          onChanged();
        } else {
          firstDeployedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public Builder clearFirstDeployed() {
        if (firstDeployedBuilder_ == null) {
          firstDeployed_ = null;
          onChanged();
        } else {
          firstDeployed_ = null;
          firstDeployedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getFirstDeployedBuilder() {
        
        onChanged();
        return getFirstDeployedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getFirstDeployedOrBuilder() {
        if (firstDeployedBuilder_ != null) {
          return firstDeployedBuilder_.getMessageOrBuilder();
        } else {
          return firstDeployed_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : firstDeployed_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp first_deployed = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getFirstDeployedFieldBuilder() {
        if (firstDeployedBuilder_ == null) {
          firstDeployedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getFirstDeployed(),
                  getParentForChildren(),
                  isClean());
          firstDeployed_ = null;
        }
        return firstDeployedBuilder_;
      }

      private com.google.protobuf.Timestamp lastDeployed_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastDeployedBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public boolean hasLastDeployed() {
        return lastDeployedBuilder_ != null || lastDeployed_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public com.google.protobuf.Timestamp getLastDeployed() {
        if (lastDeployedBuilder_ == null) {
          return lastDeployed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastDeployed_;
        } else {
          return lastDeployedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public Builder setLastDeployed(com.google.protobuf.Timestamp value) {
        if (lastDeployedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastDeployed_ = value;
          onChanged();
        } else {
          lastDeployedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public Builder setLastDeployed(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastDeployedBuilder_ == null) {
          lastDeployed_ = builderForValue.build();
          onChanged();
        } else {
          lastDeployedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public Builder mergeLastDeployed(com.google.protobuf.Timestamp value) {
        if (lastDeployedBuilder_ == null) {
          if (lastDeployed_ != null) {
            lastDeployed_ =
              com.google.protobuf.Timestamp.newBuilder(lastDeployed_).mergeFrom(value).buildPartial();
          } else {
            lastDeployed_ = value;
          }
          onChanged();
        } else {
          lastDeployedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public Builder clearLastDeployed() {
        if (lastDeployedBuilder_ == null) {
          lastDeployed_ = null;
          onChanged();
        } else {
          lastDeployed_ = null;
          lastDeployedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastDeployedBuilder() {
        
        onChanged();
        return getLastDeployedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastDeployedOrBuilder() {
        if (lastDeployedBuilder_ != null) {
          return lastDeployedBuilder_.getMessageOrBuilder();
        } else {
          return lastDeployed_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastDeployed_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp last_deployed = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastDeployedFieldBuilder() {
        if (lastDeployedBuilder_ == null) {
          lastDeployedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastDeployed(),
                  getParentForChildren(),
                  isClean());
          lastDeployed_ = null;
        }
        return lastDeployedBuilder_;
      }

      private com.google.protobuf.Timestamp deleted_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedBuilder_;
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public boolean hasDeleted() {
        return deletedBuilder_ != null || deleted_ != null;
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public com.google.protobuf.Timestamp getDeleted() {
        if (deletedBuilder_ == null) {
          return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
        } else {
          return deletedBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public Builder setDeleted(com.google.protobuf.Timestamp value) {
        if (deletedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deleted_ = value;
          onChanged();
        } else {
          deletedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public Builder setDeleted(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (deletedBuilder_ == null) {
          deleted_ = builderForValue.build();
          onChanged();
        } else {
          deletedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public Builder mergeDeleted(com.google.protobuf.Timestamp value) {
        if (deletedBuilder_ == null) {
          if (deleted_ != null) {
            deleted_ =
              com.google.protobuf.Timestamp.newBuilder(deleted_).mergeFrom(value).buildPartial();
          } else {
            deleted_ = value;
          }
          onChanged();
        } else {
          deletedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public Builder clearDeleted() {
        if (deletedBuilder_ == null) {
          deleted_ = null;
          onChanged();
        } else {
          deleted_ = null;
          deletedBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDeletedBuilder() {
        
        onChanged();
        return getDeletedFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
        if (deletedBuilder_ != null) {
          return deletedBuilder_.getMessageOrBuilder();
        } else {
          return deleted_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
        }
      }
      /**
       * <pre>
       * Deleted tracks when this object was deleted.
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp deleted = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDeletedFieldBuilder() {
        if (deletedBuilder_ == null) {
          deletedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDeleted(),
                  getParentForChildren(),
                  isClean());
          deleted_ = null;
        }
        return deletedBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * Description is human-friendly "log entry" about this release.
       * </pre>
       *
       * <code>optional string Description = 5;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Description is human-friendly "log entry" about this release.
       * </pre>
       *
       * <code>optional string Description = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Description is human-friendly "log entry" about this release.
       * </pre>
       *
       * <code>optional string Description = 5;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description is human-friendly "log entry" about this release.
       * </pre>
       *
       * <code>optional string Description = 5;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description is human-friendly "log entry" about this release.
       * </pre>
       *
       * <code>optional string Description = 5;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.release.Info)
    }

    // @@protoc_insertion_point(class_scope:hapi.release.Info)
    private static final io.winhong.pass.hapi.release.InfoOuterClass.Info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.winhong.pass.hapi.release.InfoOuterClass.Info();
    }

    public static io.winhong.pass.hapi.release.InfoOuterClass.Info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Info>
        PARSER = new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    public io.winhong.pass.hapi.release.InfoOuterClass.Info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_release_Info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_release_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027hapi/release/info.proto\022\014hapi.release\032" +
      "\037google/protobuf/timestamp.proto\032\031hapi/r" +
      "elease/status.proto\"\325\001\n\004Info\022$\n\006status\030\001" +
      " \001(\0132\024.hapi.release.Status\0222\n\016first_depl" +
      "oyed\030\002 \001(\0132\032.google.protobuf.Timestamp\0221" +
      "\n\rlast_deployed\030\003 \001(\0132\032.google.protobuf." +
      "Timestamp\022+\n\007deleted\030\004 \001(\0132\032.google.prot" +
      "obuf.Timestamp\022\023\n\013Description\030\005 \001(\tB%\n#c" +
      "n.com.chinacloud.paas.hapi.releaseb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.winhong.pass.hapi.release.StatusOuterClass.getDescriptor(),
        }, assigner);
    internal_static_hapi_release_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hapi_release_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_release_Info_descriptor,
        new java.lang.String[] { "Status", "FirstDeployed", "LastDeployed", "Deleted", "Description", });
    com.google.protobuf.TimestampProto.getDescriptor();
    io.winhong.pass.hapi.release.StatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
