// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/release/test_suite.proto

package io.winhong.pass.hapi.release;

public final class TestSuiteOuterClass {
  private TestSuiteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestSuiteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.release.TestSuite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    boolean hasStartedAt();
    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    com.google.protobuf.Timestamp getStartedAt();
    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder();

    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    boolean hasCompletedAt();
    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    com.google.protobuf.Timestamp getCompletedAt();
    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder();

    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun>
        getResultsList();
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getResults(int index);
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    int getResultsCount();
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    java.util.List<? extends io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder>
        getResultsOrBuilderList();
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * TestSuite comprises of the last run of the pre-defined test suite of a release version
   * </pre>
   *
   * Protobuf type {@code hapi.release.TestSuite}
   */
  public  static final class TestSuite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.release.TestSuite)
      TestSuiteOrBuilder {
    // Use TestSuite.newBuilder() to construct.
    private TestSuite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestSuite() {
      results_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestSuite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (startedAt_ != null) {
                subBuilder = startedAt_.toBuilder();
              }
              startedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startedAt_);
                startedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (completedAt_ != null) {
                subBuilder = completedAt_.toBuilder();
              }
              completedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(completedAt_);
                completedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                results_ = new java.util.ArrayList<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun>();
                mutable_bitField0_ |= 0x00000004;
              }
              results_.add(
                  input.readMessage(io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.winhong.pass.hapi.release.TestSuiteOuterClass.internal_static_hapi_release_TestSuite_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.winhong.pass.hapi.release.TestSuiteOuterClass.internal_static_hapi_release_TestSuite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.class, io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.Builder.class);
    }

    private int bitField0_;
    public static final int STARTED_AT_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp startedAt_;
    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    public boolean hasStartedAt() {
      return startedAt_ != null;
    }
    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    public com.google.protobuf.Timestamp getStartedAt() {
      return startedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
    }
    /**
     * <pre>
     * StartedAt indicates the date/time this test suite was kicked off
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder() {
      return getStartedAt();
    }

    public static final int COMPLETED_AT_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp completedAt_;
    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    public boolean hasCompletedAt() {
      return completedAt_ != null;
    }
    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    public com.google.protobuf.Timestamp getCompletedAt() {
      return completedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
    }
    /**
     * <pre>
     * CompletedAt indicates the date/time this test suite was completed
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder() {
      return getCompletedAt();
    }

    public static final int RESULTS_FIELD_NUMBER = 3;
    private java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun> results_;
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    public java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun> getResultsList() {
      return results_;
    }
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    public java.util.List<? extends io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getResults(int index) {
      return results_.get(index);
    }
    /**
     * <pre>
     * Results are the results of each segment of the test
     * </pre>
     *
     * <code>repeated .hapi.release.TestRun results = 3;</code>
     */
    public io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startedAt_ != null) {
        output.writeMessage(1, getStartedAt());
      }
      if (completedAt_ != null) {
        output.writeMessage(2, getCompletedAt());
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(3, results_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStartedAt());
      }
      if (completedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCompletedAt());
      }
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, results_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite)) {
        return super.equals(obj);
      }
      io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite other = (io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite) obj;

      boolean result = true;
      result = result && (hasStartedAt() == other.hasStartedAt());
      if (hasStartedAt()) {
        result = result && getStartedAt()
            .equals(other.getStartedAt());
      }
      result = result && (hasCompletedAt() == other.hasCompletedAt());
      if (hasCompletedAt()) {
        result = result && getCompletedAt()
            .equals(other.getCompletedAt());
      }
      result = result && getResultsList()
          .equals(other.getResultsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartedAt()) {
        hash = (37 * hash) + STARTED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getStartedAt().hashCode();
      }
      if (hasCompletedAt()) {
        hash = (37 * hash) + COMPLETED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCompletedAt().hashCode();
      }
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * TestSuite comprises of the last run of the pre-defined test suite of a release version
     * </pre>
     *
     * Protobuf type {@code hapi.release.TestSuite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.release.TestSuite)
        io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuiteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.winhong.pass.hapi.release.TestSuiteOuterClass.internal_static_hapi_release_TestSuite_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.winhong.pass.hapi.release.TestSuiteOuterClass.internal_static_hapi_release_TestSuite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.class, io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.Builder.class);
      }

      // Construct using io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (startedAtBuilder_ == null) {
          startedAt_ = null;
        } else {
          startedAt_ = null;
          startedAtBuilder_ = null;
        }
        if (completedAtBuilder_ == null) {
          completedAt_ = null;
        } else {
          completedAt_ = null;
          completedAtBuilder_ = null;
        }
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.winhong.pass.hapi.release.TestSuiteOuterClass.internal_static_hapi_release_TestSuite_descriptor;
      }

      public io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite getDefaultInstanceForType() {
        return io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.getDefaultInstance();
      }

      public io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite build() {
        io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite buildPartial() {
        io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite result = new io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (startedAtBuilder_ == null) {
          result.startedAt_ = startedAt_;
        } else {
          result.startedAt_ = startedAtBuilder_.build();
        }
        if (completedAtBuilder_ == null) {
          result.completedAt_ = completedAt_;
        } else {
          result.completedAt_ = completedAtBuilder_.build();
        }
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite) {
          return mergeFrom((io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite other) {
        if (other == io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite.getDefaultInstance()) return this;
        if (other.hasStartedAt()) {
          mergeStartedAt(other.getStartedAt());
        }
        if (other.hasCompletedAt()) {
          mergeCompletedAt(other.getCompletedAt());
        }
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000004);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp startedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startedAtBuilder_;
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public boolean hasStartedAt() {
        return startedAtBuilder_ != null || startedAt_ != null;
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public com.google.protobuf.Timestamp getStartedAt() {
        if (startedAtBuilder_ == null) {
          return startedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
        } else {
          return startedAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public Builder setStartedAt(com.google.protobuf.Timestamp value) {
        if (startedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startedAt_ = value;
          onChanged();
        } else {
          startedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public Builder setStartedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startedAtBuilder_ == null) {
          startedAt_ = builderForValue.build();
          onChanged();
        } else {
          startedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public Builder mergeStartedAt(com.google.protobuf.Timestamp value) {
        if (startedAtBuilder_ == null) {
          if (startedAt_ != null) {
            startedAt_ =
              com.google.protobuf.Timestamp.newBuilder(startedAt_).mergeFrom(value).buildPartial();
          } else {
            startedAt_ = value;
          }
          onChanged();
        } else {
          startedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public Builder clearStartedAt() {
        if (startedAtBuilder_ == null) {
          startedAt_ = null;
          onChanged();
        } else {
          startedAt_ = null;
          startedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartedAtBuilder() {
        
        onChanged();
        return getStartedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder() {
        if (startedAtBuilder_ != null) {
          return startedAtBuilder_.getMessageOrBuilder();
        } else {
          return startedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
        }
      }
      /**
       * <pre>
       * StartedAt indicates the date/time this test suite was kicked off
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp started_at = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartedAtFieldBuilder() {
        if (startedAtBuilder_ == null) {
          startedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStartedAt(),
                  getParentForChildren(),
                  isClean());
          startedAt_ = null;
        }
        return startedAtBuilder_;
      }

      private com.google.protobuf.Timestamp completedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> completedAtBuilder_;
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public boolean hasCompletedAt() {
        return completedAtBuilder_ != null || completedAt_ != null;
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public com.google.protobuf.Timestamp getCompletedAt() {
        if (completedAtBuilder_ == null) {
          return completedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
        } else {
          return completedAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public Builder setCompletedAt(com.google.protobuf.Timestamp value) {
        if (completedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          completedAt_ = value;
          onChanged();
        } else {
          completedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public Builder setCompletedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (completedAtBuilder_ == null) {
          completedAt_ = builderForValue.build();
          onChanged();
        } else {
          completedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public Builder mergeCompletedAt(com.google.protobuf.Timestamp value) {
        if (completedAtBuilder_ == null) {
          if (completedAt_ != null) {
            completedAt_ =
              com.google.protobuf.Timestamp.newBuilder(completedAt_).mergeFrom(value).buildPartial();
          } else {
            completedAt_ = value;
          }
          onChanged();
        } else {
          completedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public Builder clearCompletedAt() {
        if (completedAtBuilder_ == null) {
          completedAt_ = null;
          onChanged();
        } else {
          completedAt_ = null;
          completedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCompletedAtBuilder() {
        
        onChanged();
        return getCompletedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder() {
        if (completedAtBuilder_ != null) {
          return completedAtBuilder_.getMessageOrBuilder();
        } else {
          return completedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
        }
      }
      /**
       * <pre>
       * CompletedAt indicates the date/time this test suite was completed
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp completed_at = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCompletedAtFieldBuilder() {
        if (completedAtBuilder_ == null) {
          completedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCompletedAt(),
                  getParentForChildren(),
                  isClean());
          completedAt_ = null;
        }
        return completedAtBuilder_;
      }

      private java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          results_ = new java.util.ArrayList<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun>(results_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.winhong.pass.hapi.release.TestRunOuterClass.TestRun, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder, io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder> resultsBuilder_;

      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder setResults(
          int index, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder setResults(
          int index, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder addResults(io.winhong.pass.hapi.release.TestRunOuterClass.TestRun value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder addResults(
          int index, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder addResults(
          io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder addResults(
          int index, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends io.winhong.pass.hapi.release.TestRunOuterClass.TestRun> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public java.util.List<? extends io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.getDefaultInstance());
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.getDefaultInstance());
      }
      /**
       * <pre>
       * Results are the results of each segment of the test
       * </pre>
       *
       * <code>repeated .hapi.release.TestRun results = 3;</code>
       */
      public java.util.List<io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.winhong.pass.hapi.release.TestRunOuterClass.TestRun, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder, io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.winhong.pass.hapi.release.TestRunOuterClass.TestRun, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder, io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.release.TestSuite)
    }

    // @@protoc_insertion_point(class_scope:hapi.release.TestSuite)
    private static final io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite();
    }

    public static io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestSuite>
        PARSER = new com.google.protobuf.AbstractParser<TestSuite>() {
      public TestSuite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestSuite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestSuite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestSuite> getParserForType() {
      return PARSER;
    }

    public io.winhong.pass.hapi.release.TestSuiteOuterClass.TestSuite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_release_TestSuite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_release_TestSuite_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035hapi/release/test_suite.proto\022\014hapi.re" +
      "lease\032\037google/protobuf/timestamp.proto\032\033" +
      "hapi/release/test_run.proto\"\225\001\n\tTestSuit" +
      "e\022.\n\nstarted_at\030\001 \001(\0132\032.google.protobuf." +
      "Timestamp\0220\n\014completed_at\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\022&\n\007results\030\003 \003(\0132\025.h" +
      "api.release.TestRunB%\n#cn.com.chinacloud" +
      ".paas.hapi.releaseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.winhong.pass.hapi.release.TestRunOuterClass.getDescriptor(),
        }, assigner);
    internal_static_hapi_release_TestSuite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hapi_release_TestSuite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_release_TestSuite_descriptor,
        new java.lang.String[] { "StartedAt", "CompletedAt", "Results", });
    com.google.protobuf.TimestampProto.getDescriptor();
    io.winhong.pass.hapi.release.TestRunOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
