// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/release/test_run.proto

package io.winhong.pass.hapi.release;

public final class TestRunOuterClass {
  private TestRunOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestRunOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.release.TestRun)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .hapi.release.TestRun.Status status = 2;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .hapi.release.TestRun.Status status = 2;</code>
     */
    io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status getStatus();

    /**
     * <code>optional string info = 3;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 3;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    boolean hasStartedAt();
    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    com.google.protobuf.Timestamp getStartedAt();
    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    boolean hasCompletedAt();
    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    com.google.protobuf.Timestamp getCompletedAt();
    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder();
  }
  /**
   * Protobuf type {@code hapi.release.TestRun}
   */
  public  static final class TestRun extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.release.TestRun)
      TestRunOrBuilder {
    // Use TestRun.newBuilder() to construct.
    private TestRun(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestRun() {
      name_ = "";
      status_ = 0;
      info_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestRun(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              info_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (startedAt_ != null) {
                subBuilder = startedAt_.toBuilder();
              }
              startedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startedAt_);
                startedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (completedAt_ != null) {
                subBuilder = completedAt_.toBuilder();
              }
              completedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(completedAt_);
                completedAt_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.winhong.pass.hapi.release.TestRunOuterClass.internal_static_hapi_release_TestRun_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.winhong.pass.hapi.release.TestRunOuterClass.internal_static_hapi_release_TestRun_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.class, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder.class);
    }

    /**
     * Protobuf enum {@code hapi.release.TestRun.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(1),
      /**
       * <code>FAILURE = 2;</code>
       */
      FAILURE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>FAILURE = 2;</code>
       */
      public static final int FAILURE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SUCCESS;
          case 2: return FAILURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:hapi.release.TestRun.Status)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>optional .hapi.release.TestRun.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .hapi.release.TestRun.Status status = 2;</code>
     */
    public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status getStatus() {
      io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status result = io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.valueOf(status_);
      return result == null ? io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.UNRECOGNIZED : result;
    }

    public static final int INFO_FIELD_NUMBER = 3;
    private volatile java.lang.Object info_;
    /**
     * <code>optional string info = 3;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>optional string info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTED_AT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp startedAt_;
    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    public boolean hasStartedAt() {
      return startedAt_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    public com.google.protobuf.Timestamp getStartedAt() {
      return startedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder() {
      return getStartedAt();
    }

    public static final int COMPLETED_AT_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp completedAt_;
    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    public boolean hasCompletedAt() {
      return completedAt_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    public com.google.protobuf.Timestamp getCompletedAt() {
      return completedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder() {
      return getCompletedAt();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (status_ != io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.UNKNOWN.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!getInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, info_);
      }
      if (startedAt_ != null) {
        output.writeMessage(4, getStartedAt());
      }
      if (completedAt_ != null) {
        output.writeMessage(5, getCompletedAt());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (status_ != io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!getInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, info_);
      }
      if (startedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getStartedAt());
      }
      if (completedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCompletedAt());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.winhong.pass.hapi.release.TestRunOuterClass.TestRun)) {
        return super.equals(obj);
      }
      io.winhong.pass.hapi.release.TestRunOuterClass.TestRun other = (io.winhong.pass.hapi.release.TestRunOuterClass.TestRun) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && status_ == other.status_;
      result = result && getInfo()
          .equals(other.getInfo());
      result = result && (hasStartedAt() == other.hasStartedAt());
      if (hasStartedAt()) {
        result = result && getStartedAt()
            .equals(other.getStartedAt());
      }
      result = result && (hasCompletedAt() == other.hasCompletedAt());
      if (hasCompletedAt()) {
        result = result && getCompletedAt()
            .equals(other.getCompletedAt());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      if (hasStartedAt()) {
        hash = (37 * hash) + STARTED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getStartedAt().hashCode();
      }
      if (hasCompletedAt()) {
        hash = (37 * hash) + COMPLETED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCompletedAt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.winhong.pass.hapi.release.TestRunOuterClass.TestRun prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hapi.release.TestRun}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.release.TestRun)
        io.winhong.pass.hapi.release.TestRunOuterClass.TestRunOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.winhong.pass.hapi.release.TestRunOuterClass.internal_static_hapi_release_TestRun_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.winhong.pass.hapi.release.TestRunOuterClass.internal_static_hapi_release_TestRun_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.class, io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Builder.class);
      }

      // Construct using io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        status_ = 0;

        info_ = "";

        if (startedAtBuilder_ == null) {
          startedAt_ = null;
        } else {
          startedAt_ = null;
          startedAtBuilder_ = null;
        }
        if (completedAtBuilder_ == null) {
          completedAt_ = null;
        } else {
          completedAt_ = null;
          completedAtBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.winhong.pass.hapi.release.TestRunOuterClass.internal_static_hapi_release_TestRun_descriptor;
      }

      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getDefaultInstanceForType() {
        return io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.getDefaultInstance();
      }

      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun build() {
        io.winhong.pass.hapi.release.TestRunOuterClass.TestRun result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun buildPartial() {
        io.winhong.pass.hapi.release.TestRunOuterClass.TestRun result = new io.winhong.pass.hapi.release.TestRunOuterClass.TestRun(this);
        result.name_ = name_;
        result.status_ = status_;
        result.info_ = info_;
        if (startedAtBuilder_ == null) {
          result.startedAt_ = startedAt_;
        } else {
          result.startedAt_ = startedAtBuilder_.build();
        }
        if (completedAtBuilder_ == null) {
          result.completedAt_ = completedAt_;
        } else {
          result.completedAt_ = completedAtBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.winhong.pass.hapi.release.TestRunOuterClass.TestRun) {
          return mergeFrom((io.winhong.pass.hapi.release.TestRunOuterClass.TestRun)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.winhong.pass.hapi.release.TestRunOuterClass.TestRun other) {
        if (other == io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          onChanged();
        }
        if (other.hasStartedAt()) {
          mergeStartedAt(other.getStartedAt());
        }
        if (other.hasCompletedAt()) {
          mergeCompletedAt(other.getCompletedAt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.winhong.pass.hapi.release.TestRunOuterClass.TestRun parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.winhong.pass.hapi.release.TestRunOuterClass.TestRun) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .hapi.release.TestRun.Status status = 2;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .hapi.release.TestRun.Status status = 2;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .hapi.release.TestRun.Status status = 2;</code>
       */
      public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status getStatus() {
        io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status result = io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.valueOf(status_);
        return result == null ? io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .hapi.release.TestRun.Status status = 2;</code>
       */
      public Builder setStatus(io.winhong.pass.hapi.release.TestRunOuterClass.TestRun.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .hapi.release.TestRun.Status status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 3;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder clearInfo() {
        
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        info_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp startedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startedAtBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public boolean hasStartedAt() {
        return startedAtBuilder_ != null || startedAt_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public com.google.protobuf.Timestamp getStartedAt() {
        if (startedAtBuilder_ == null) {
          return startedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
        } else {
          return startedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public Builder setStartedAt(com.google.protobuf.Timestamp value) {
        if (startedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startedAt_ = value;
          onChanged();
        } else {
          startedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public Builder setStartedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startedAtBuilder_ == null) {
          startedAt_ = builderForValue.build();
          onChanged();
        } else {
          startedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public Builder mergeStartedAt(com.google.protobuf.Timestamp value) {
        if (startedAtBuilder_ == null) {
          if (startedAt_ != null) {
            startedAt_ =
              com.google.protobuf.Timestamp.newBuilder(startedAt_).mergeFrom(value).buildPartial();
          } else {
            startedAt_ = value;
          }
          onChanged();
        } else {
          startedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public Builder clearStartedAt() {
        if (startedAtBuilder_ == null) {
          startedAt_ = null;
          onChanged();
        } else {
          startedAt_ = null;
          startedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartedAtBuilder() {
        
        onChanged();
        return getStartedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartedAtOrBuilder() {
        if (startedAtBuilder_ != null) {
          return startedAtBuilder_.getMessageOrBuilder();
        } else {
          return startedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : startedAt_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp started_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartedAtFieldBuilder() {
        if (startedAtBuilder_ == null) {
          startedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStartedAt(),
                  getParentForChildren(),
                  isClean());
          startedAt_ = null;
        }
        return startedAtBuilder_;
      }

      private com.google.protobuf.Timestamp completedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> completedAtBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public boolean hasCompletedAt() {
        return completedAtBuilder_ != null || completedAt_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public com.google.protobuf.Timestamp getCompletedAt() {
        if (completedAtBuilder_ == null) {
          return completedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
        } else {
          return completedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public Builder setCompletedAt(com.google.protobuf.Timestamp value) {
        if (completedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          completedAt_ = value;
          onChanged();
        } else {
          completedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public Builder setCompletedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (completedAtBuilder_ == null) {
          completedAt_ = builderForValue.build();
          onChanged();
        } else {
          completedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public Builder mergeCompletedAt(com.google.protobuf.Timestamp value) {
        if (completedAtBuilder_ == null) {
          if (completedAt_ != null) {
            completedAt_ =
              com.google.protobuf.Timestamp.newBuilder(completedAt_).mergeFrom(value).buildPartial();
          } else {
            completedAt_ = value;
          }
          onChanged();
        } else {
          completedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public Builder clearCompletedAt() {
        if (completedAtBuilder_ == null) {
          completedAt_ = null;
          onChanged();
        } else {
          completedAt_ = null;
          completedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCompletedAtBuilder() {
        
        onChanged();
        return getCompletedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCompletedAtOrBuilder() {
        if (completedAtBuilder_ != null) {
          return completedAtBuilder_.getMessageOrBuilder();
        } else {
          return completedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : completedAt_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp completed_at = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCompletedAtFieldBuilder() {
        if (completedAtBuilder_ == null) {
          completedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCompletedAt(),
                  getParentForChildren(),
                  isClean());
          completedAt_ = null;
        }
        return completedAtBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.release.TestRun)
    }

    // @@protoc_insertion_point(class_scope:hapi.release.TestRun)
    private static final io.winhong.pass.hapi.release.TestRunOuterClass.TestRun DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.winhong.pass.hapi.release.TestRunOuterClass.TestRun();
    }

    public static io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestRun>
        PARSER = new com.google.protobuf.AbstractParser<TestRun>() {
      public TestRun parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestRun(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestRun> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestRun> getParserForType() {
      return PARSER;
    }

    public io.winhong.pass.hapi.release.TestRunOuterClass.TestRun getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_release_TestRun_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_release_TestRun_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033hapi/release/test_run.proto\022\014hapi.rele" +
      "ase\032\037google/protobuf/timestamp.proto\"\346\001\n" +
      "\007TestRun\022\014\n\004name\030\001 \001(\t\022,\n\006status\030\002 \001(\0162\034" +
      ".hapi.release.TestRun.Status\022\014\n\004info\030\003 \001" +
      "(\t\022.\n\nstarted_at\030\004 \001(\0132\032.google.protobuf" +
      ".Timestamp\0220\n\014completed_at\030\005 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\"/\n\006Status\022\013\n\007UNKNOW" +
      "N\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002B%\n#cn.com." +
      "chinacloud.paas.hapi.releaseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_hapi_release_TestRun_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hapi_release_TestRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_release_TestRun_descriptor,
        new java.lang.String[] { "Name", "Status", "Info", "StartedAt", "CompletedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
